const lineStates = [
  { value: "none", changing: false },
  { value: "yin", changing: false },
  { value: "yin", changing: true },
  { value: "yang", changing: false },
  { value: "yang", changing: true },
];

const trigramStates = [
  { name: "None", trigramLines: ["none", "none", "none"] },
  { name: "Heaven", trigramLines: ["yang", "yang", "yang"] },
  { name: "Earth", trigramLines: ["yin", "yin", "yin"] },
  { name: "Thunder", trigramLines: ["yin", "yin", "yang"] },
  { name: "Wind", trigramLines: ["yang", "yang", "yin"] },
  { name: "Water", trigramLines: ["yin", "yang", "yin"] },
  { name: "Mountain", trigramLines: ["yang", "yin", "yin"] },
  { name: "Fire", trigramLines: ["yang", "yin", "yang"] },
  { name: "Lake", trigramLines: ["yin", "yang", "yang"] },
];

const hexagramStates = [
  { number: 0, trigrams: ["None", "None"] },
  { number: 1, trigrams: ["Heaven", "Heaven"], unicode: "\u4DC0" },
  { number: 2, trigrams: ["Earth", "Earth"], unicode: "\u4DC1" },
  { number: 3, trigrams: ["Water", "Thunder"], unicode: "\u4DC2" },
  { number: 4, trigrams: ["Mountain", "Water"], unicode: "\u4DC3" },
  { number: 5, trigrams: ["Water", "Heaven"], unicode: "\u4DC4" },
  { number: 6, trigrams: ["Heaven", "Water"], unicode: "\u4DC5" },
  { number: 7, trigrams: ["Earth", "Water"], unicode: "\u4DC6" },
  { number: 8, trigrams: ["Water", "Earth"], unicode: "\u4DC7" },
  { number: 9, trigrams: ["Wind", "Heaven"], unicode: "\u4DC8" },
  { number: 10, trigrams: ["Heaven", "Lake"], unicode: "\u4DC9" },
  { number: 11, trigrams: ["Earth", "Heaven"], unicode: "\u4DCA" },
  { number: 12, trigrams: ["Heaven", "Earth"], unicode: "\u4DCB" },
  { number: 13, trigrams: ["Heaven", "Fire"], unicode: "\u4DCC" },
  { number: 14, trigrams: ["Fire", "Heaven"], unicode: "\u4DCD" },
  { number: 15, trigrams: ["Earth", "Mountain"], unicode: "\u4DCE" },
  { number: 16, trigrams: ["Thunder", "Earth"], unicode: "\u4DCF" },
  { number: 17, trigrams: ["Lake", "Thunder"], unicode: "\u4DD0" },
  { number: 18, trigrams: ["Mountain", "Wind"], unicode: "\u4DD1" },
  { number: 19, trigrams: ["Earth", "Lake"], unicode: "\u4DD2" },
  { number: 20, trigrams: ["Wind", "Earth"], unicode: "\u4DD3" },
  { number: 21, trigrams: ["Fire", "Thunder"], unicode: "\u4DD4" },
  { number: 22, trigrams: ["Mountain", "Fire"], unicode: "\u4DD5" },
  { number: 23, trigrams: ["Mountain", "Earth"], unicode: "\u4DD6" },
  { number: 24, trigrams: ["Earth", "Thunder"], unicode: "\u4DD7" },
  { number: 25, trigrams: ["Heaven", "Thunder"], unicode: "\u4DD8" },
  { number: 26, trigrams: ["Mountain", "Heaven"], unicode: "\u4DD9" },
  { number: 27, trigrams: ["Mountain", "Thunder"], unicode: "\u4DDA" },
  { number: 28, trigrams: ["Lake", "Wind"], unicode: "\u4DDB" },
  { number: 29, trigrams: ["Water", "Water"], unicode: "\u4DDC" },
  { number: 30, trigrams: ["Fire", "Fire"], unicode: "\u4DDD" },
  { number: 31, trigrams: ["Lake", "Mountain"], unicode: "\u4DDE" },
  { number: 32, trigrams: ["Thunder", "Wind"], unicode: "\u4DDF" },
  { number: 33, trigrams: ["Heaven", "Mountain"], unicode: "\u4DE0" },
  { number: 34, trigrams: ["Thunder", "Heaven"], unicode: "\u4DE1" },
  { number: 35, trigrams: ["Fire", "Earth"], unicode: "\u4DE2" },
  { number: 36, trigrams: ["Earth", "Fire"], unicode: "\u4DE3" },
  { number: 37, trigrams: ["Wind", "Fire"], unicode: "\u4DE4" },
  { number: 38, trigrams: ["Fire", "Wind"], unicode: "\u4DE5" },
  { number: 39, trigrams: ["Water", "Mountain"], unicode: "\u4DE6" },
  { number: 40, trigrams: ["Thunder", "Water"], unicode: "\u4DE7" },
  { number: 41, trigrams: ["Mountain", "Lake"], unicode: "\u4DE8" },
  { number: 42, trigrams: ["Wind", "Thunder"], unicode: "\u4DE9" },
  { number: 43, trigrams: ["Lake", "Heaven"], unicode: "\u4DEA" },
  { number: 44, trigrams: ["Heaven", "Wind"], unicode: "\u4DEB" },
  { number: 45, trigrams: ["Lake", "Earth"], unicode: "\u4DEC" },
  { number: 46, trigrams: ["Earth", "Wind"], unicode: "\u4DED" },
  { number: 47, trigrams: ["Lake", "Water"], unicode: "\u4DEE" },
  { number: 48, trigrams: ["Water", "Wind"], unicode: "\u4DEF" },
  { number: 49, trigrams: ["Lake", "Fire"], unicode: "\u4DF0" },
  { number: 50, trigrams: ["Fire", "Wind"], unicode: "\u4DF1" },
  { number: 51, trigrams: ["Thunder", "Thunder"], unicode: "\u4DF2" },
  { number: 52, trigrams: ["Mountain", "Mountain"], unicode: "\u4DF3" },
  { number: 53, trigrams: ["Wind", "Mountain"], unicode: "\u4DF4" },
  { number: 54, trigrams: ["Thunder", "Lake"], unicode: "\u4DF5" },
  { number: 55, trigrams: ["Thunder", "Fire"], unicode: "\u4DF6" },
  { number: 56, trigrams: ["Fire", "Mountain"], unicode: "\u4DF7" },
  { number: 57, trigrams: ["Wind", "Wind"], unicode: "\u4DF8" },
  { number: 58, trigrams: ["Lake", "Lake"], unicode: "\u4DF9" },
  { number: 59, trigrams: ["Wind", "Water"], unicode: "\u4DFA" },
  { number: 60, trigrams: ["Water", "Lake"], unicode: "\u4DFB" },
  { number: 61, trigrams: ["Wind", "Lake"], unicode: "\u4DFC" },
  { number: 62, trigrams: ["Thunder", "Mountain"], unicode: "\u4DFD" },
  { number: 63, trigrams: ["Water", "Fire"], unicode: "\u4DFE" },
  { number: 64, trigrams: ["Fire", "Water"], unicode: "\u4DFF" },
];

const emptyTrigram = trigramStates[0];
const emptyHexagram = hexagramStates[0];

export {
  lineStates,
  trigramStates,
  hexagramStates,
  emptyTrigram,
  emptyHexagram,
};
